name: CI

# Trigger this workflow on push or pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment (version 20)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install npm dependencies using clean install
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the TypeScript project (production build)
      - name: Build TypeScript (production)
        run: npm run build

      # Step 5: Run local tests using Node.js and TypeScript (with mocks)
      - name: Run tests (local Node.js + mocks)
        run: npm test